Drive
recordrobotics/2022_Rewrite pull request #21
Opened 2022-05-03 00:26 UTC by DragonSM

2022-05-03 00:55 UTC, fielia requested changes
pls dont be offended by my succinct comments (and spelling mistakes)

2022-05-03 00:55 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotMap.java
> +	public class DriveBase {
alphabetize???

2022-05-03 00:55 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	private void RunLinearDrive(){
camel font

2022-05-03 00:55 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/DriveTrain.java
> +	private CANSparkMax[] _leftMotors = { new CANSparkMax(RobotMap.DriveBase.LEFT_FRONT_MOTOR_PORT, MotorType.kBrushless),
_leftMotors and _rightMotors are only used to declare the MotorGroups. could you remove them?

2022-05-03 01:28 UTC, vladaviedov requested changes

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/RobotMap.java
> +	public class DriveBase {
Also missing comments on types of ports

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	@SuppressWarnings({"unused", "PMD.SingularField"})
Remove this

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/DriveTrain.java
> +public class DriveTrain extends SubsystemBase {
Is there a reason for the Train part? :)
Can we just name it Drive?

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/DriveTrain.java
> +	private CANSparkMax[] _leftMotors = { new CANSparkMax(RobotMap.DriveBase.LEFT_FRONT_MOTOR_PORT, MotorType.kBrushless),
agree

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/DriveTrain.java
> +	@SuppressWarnings({"PMD.UnnecessaryConstructor", "PMD.UncommentedEmptyConstructor"})
The constructor should be stopping motors just in case
Remove the supresswarnings annotation

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +		RunLinearDrive();
RunLinearDrive should just be moved into execute if it's the only thing there

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	private void stopDriveMotors(){
Redundant

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	@Override
isFinished returns false by default, no need to override it

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	public void end(boolean interrupted) {}
The command should stop the motors when ending

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +	 * Creates a new ExampleCommand.
Remove/Change these leftover comments

2022-05-03 01:28 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDriveTrain.java
> +		_driveTrain.getDifferentialDrive().arcadeDrive(_controls.getDriveLong() * 0.45, _controls.getDriveLat() * 0.45);
This logic should be handled by the subsystem
Putting it here breaks OOP

2022-05-10 00:49 UTC, vladaviedov submitted a review, later dismissed

2022-05-10 01:33 UTC, fielia requested changes

2022-05-10 01:33 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotMap.java
> +	public class DriveBase {
u still need to alphabetize drivebase (i believe it goes below climbers?)

2022-05-10 01:33 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private CANSparkMax[] _leftMotors = {
you also need to eliminate _leftMotors and _rightMotors, because they're only used for the motor controller groups.

2022-05-10 01:33 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +		_differentialDrive.arcadeDrive(Subsystems.limitSpeed(latSpeed),
maybe add a comment explaining when lat and long are switched?

2022-05-10 01:50 UTC, fielia approved these changes
I'd personally make the comment a javadoc one, for style purposes, but ig it's fine either way.

2022-05-10 01:53 UTC, vladaviedov commented
Eh, it's a comment about the internal quirks of WPILib
It's like a "private" comment so to say

2022-05-10 02:01 UTC, merged