Auto Drive
recordrobotics/2022_Rewrite pull request #37
Opened 2022-05-11 20:23 UTC by fielia

2022-06-17 00:35 UTC, vladaviedov reviewed
Looks okay, but a few readability comments

2022-06-17 00:35 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	public double getRightEncoder() {
Is there a reason to expose (public) these methods?

2022-06-17 01:58 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	public double getRightEncoder() {
ah
i think i meant to add these in the future somewhere, then getPosition() came around

2022-08-24 19:21 UTC, vladaviedov requested changes

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		return _drive.getPosition() * _direction.value() >= _targetDistance * _direction.value();
This looks strange, why is direction value on both sides?

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveToRange.java
> +	 * resets encoders and starts move
This comment does not describe the function

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in FEET
It's not in feet
https://codedocs.revrobotics.com/java/com/revrobotics/relativeencoder#getPosition()

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
IIRC this is wrong, longSpeed should be forward/backward movement

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveToRange.java
> +	 * @param targetRange target distance to go to (positive, millimeters)
If this is in mm, then drive should definitely not report feet

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		_drive.move(0, _speed * _direction.value());
Spin?

2022-08-24 19:21 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +	 * resets encoders and starts move
Does not describe function, although it does make sense to reset the encoders here

2022-08-24 20:53 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		return _drive.getPosition() * _direction.value() >= _targetDistance * _direction.value();
Honestly have no idea.

2022-08-24 20:56 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
i don't think so...

2022-08-24 20:57 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in FEET
then how would i convert it into mm

2022-08-24 20:59 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		_drive.move(0, _speed * _direction.value());
what?

2022-08-24 21:00 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in FEET
You would need the gearbox ratios which I do not know

2022-08-24 21:02 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
I programmed long to be forward/backward and lat to be left/right in control.
There was an issue where this didn't work with drive, but it's because arcadeDrive expects rotations around an axis.
This is accounted for by this method and expects long lat as documented in control.

2022-08-24 21:03 UTC, vladaviedov requested changes

2022-08-24 21:03 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		_drive.move(0, _speed * _direction.value());
This will cause the robot to spin, see my other comment

2022-08-24 21:03 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveToRange.java
> +		_drive.resetEncoders();
Don't think it makes a difference here

2022-08-24 21:04 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in FEET
...but ur engineering lead...

2022-08-24 21:05 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
could I just switch the names around?

2022-08-24 21:05 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
so it makes sense? cuz ik that's what I did before

2022-08-24 21:06 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in FEET
Not mechanical

2022-08-24 21:07 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param longSpeed rotation speed (positive is clockwise)
The naming is correct here
First argument should be forward/backward input
Second argument should be left/right input

2022-08-26 14:46 UTC, vladaviedov requested changes
Some small changes still required.
Also need to find out drive gearbox ratios.

2022-08-26 14:46 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> -		_differentialDrive.arcadeDrive(Subsystems.limitSpeed(latSpeed),
Revert this as well

2022-08-26 18:58 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> -		_differentialDrive.arcadeDrive(Subsystems.limitSpeed(latSpeed),
oops

2022-09-15 20:51 UTC, fielia commented
oh uh

might've forgotten this existed
ill work on it when i go in next, prolly next monday

2022-12-25 04:46 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveDistance.java
> +		double dx = _targetDistance - _drive.getPosition();
Just realized that this doesn't make much sense.
Resetting encoders should ensure that the call to getPosition returns 0.0

2022-12-25 04:48 UTC, vladaviedov commented
Still some places where logic/comments need to be changed

2022-12-25 15:19 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @return The value of the right encoder in rotations
Change this to the actual unit outputted later.
This should give back length, not rotations.

2022-12-25 15:19 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveToRange.java
> +		return _sensors.getDistance() <= _targetRange;
Missed this as well last time, but this wouldn't work if the initial sensor reading is less than target

2022-12-25 16:32 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/auto/AutoMoveToRange.java
> +		return _sensors.getDistance() <= _targetRange;
i think that's the point
if the sensors are already too close, the command doesn't do anything

2023-01-06 03:09 UTC, vladaviedov approved these changes

2023-01-06 03:13 UTC, merged