Acceleration/deceleration
recordrobotics/2022_Rewrite pull request #46
Opened 2022-12-23 01:07 UTC by ElementalAlly

Acceleration ramping with separation through classes. This is tested and working.

2022-12-23 01:14 UTC, ElementalAlly commented
I don't know how the heck to resolve the conflicts in RobotContainer...

2022-12-23 01:25 UTC, fielia requested changes
I'm prolly just being nitpicky, but i think ur concepts and executions are great!
also, i may have missed some stuff here

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/Constants.java
>  }
Do all these constants need to be here? Zero, for example, feels unnecessary
also, are these values going to be used anywhere except manualdrive? this file is for constants that will be used in multiple files. otherwise, just have them declared locally

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	private Boolean _rampingBool;
could this name be more descriptive? i think something like _ramp or _isRamping is better

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		}
this doesn't need to be a nested if
in retrospect, this may be for reading purposes, in which case that should be fine

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		_maxScaling = maxScaling;
This may just be me being dumb, but what's the point of maxScaling? what does it do?

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	private Boolean _rampingBool;
I think in general, most of your names could be more descriptive (ex: i have no idea what the drive control ramping vars are for
an alternative for this, if u can't think up better names, is to use javadoc comments to describe the variables (here, u can use sentences lol)

2022-12-23 01:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +	public double calcNextCtrlScale(double currControlScale, double input) {
what does this function do? adding javadoc comments here, to ur contructor, and to ur variables should help with readability (and help us not have to decipher ur entire code when calling the function again)

2022-12-25 04:32 UTC, vladaviedov requested changes
Messy; needs documentation

2022-12-25 04:32 UTC, vladaviedov commented on build.gradle
> + pmd {
Revert file, please

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/Constants.java
>  }
I second this.
ZERO is also a poor name choice, it's no better than leaving the magic number in the code, give it a name for what it actually represents.

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +			new ManualDrive(_drive, _controlInput, true));
This should not be here.
See initTeleopCommands() for the proper way to create commands.
Note that the for loop schedules all commands inside _teleopPairs

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +public class ControlRamping {
First, the 'control' directory is meant for abstracting away the interaction between input devices and robot code.
Second, this class should really be a function, it doesn't make much sense to allocate an object for it.

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	public ManualDrive(Drive drive, IControlInput controls, Boolean rampingBool) {
This actually introduces a possible NPE with no benefit.
Use the primitive version of boolean (lowercase) instead.

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		if(nextCtrlScale < -1.0 || nextCtrlScale > 1.0) {
Replace with Math.abs call

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +	public double calcNextCtrlScale(double currControlScale, double input) {
Yes, this function definitely needs some comments, it's very hard to understand.

2022-12-25 04:32 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		}
This whole construction can be converted into a single 'if' statement

2022-12-25 04:52 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +			new ManualDrive(_drive, _controlInput, true));
I realize this was probably from the merge conflict, but it still needs to be changed

2022-12-25 13:50 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	public ManualDrive(Drive drive, IControlInput controls, Boolean rampingBool) {
for the people, an NPE is a Null Pointer Exception

2022-12-26 21:46 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		_maxScaling = maxScaling;
Maxscaling enables the acceleration to scale faster if the control stick is pushed all the way forwards/backwards.

2022-12-26 22:47 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +		_maxScaling = maxScaling;
use javadocs to explain that in code

2022-12-30 20:03 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/Constants.java
>  }
As an example, COMMANDS_TAB and DATA_TAB are pretty specific, as there's only one thing they could be referring to (shuffleboard). They also are/could be used in many files, like Climbers, Rotator, and Sensors. These types of constants go in Constants.java.

2022-12-30 20:05 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +			new ManualDrive(_drive, _controlInput, true));
I think Vlad is pointing at the third parameter in the ManualDrive() call. The issue is it doesn't align with the call in initTeleopCommands().

2022-12-30 20:08 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	public ManualDrive(Drive drive, IControlInput controls, Boolean rampingBool) {
I'm curious why you decided to import the value of rampingBool, instead of having it set as a constant. The only reason I can think of to change whether we ramp the accel/decel (if that's what _rampingBool is supposed to do) in the same program call is if we want to have a shuffleboard button switch whether we ramp or not. However, there is a much better way of doing this than adding a parameter to the constructor.

2022-12-30 20:14 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +	public ControlRamping (double higherTimeScale, double lowerTimeScale, boolean maxScaling) {
Similar to my comment about the ManualDrive constructor, why have the maxScaling boolean as a parameter, rather than a constant?

2022-12-31 00:59 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	public ManualDrive(Drive drive, IControlInput controls, Boolean rampingBool) {
I don't know how to interface with shuffleboard, and if you could help me with that (that activation/deactivation is what I had in mind), that would be great! Thanks!

2022-12-31 01:00 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +	public ControlRamping (double higherTimeScale, double lowerTimeScale, boolean maxScaling) {
This is in case I want to use ramping that doesn't accelerate faster when the control stick is all the way forwards, and using this setup, I can change that based on the subsystem the ramper is being used on.

2022-12-31 01:33 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/control/ControlRamping.java
> +public class ControlRamping {
Here, I make it a separate class so it can be used throughout the code in different subsystems, instead of having to manually copy the code to each :) .

2022-12-31 01:48 UTC, ElementalAlly commented
I believe I have made all the changes you guys wanted. Thanks for the help and review, and if you could help me or teach me how to interface with Shuffleboard to be able to turn on and off the ramping, that would be great! Thanks so much!

2022-12-31 02:36 UTC, fielia requested changes

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/Constants.java
> +	public final static double MOVEMENT_EXPONENTIAL_BASE = 10.0;
This variable name still seems vague. It sounds like '10' is supposed to be the x value in x^y, but if this is going to be used in Ramping, i don't think it'll go there

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput, true)));
I don't think this was fixed yet. There's still an error in this file, and I'm not even sure the third parameter even belongs

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
I don't think this was fixed. Instead of util, I think this would best be placed in .commands.manual, as that's where this code would be used. I also think, as Vlad stated earlier, this entire object could be a function in another object.
Also, control files are different in our project. They represent control schemes. I suggest changing your file name.

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	 */
I don't think this is proper javadoc formatting. I will probably reach out soon and show you how to use javadocs.

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +
This new line shouldn't be there

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	private final static double CTRL_NEUTRAL_POSITION = 0.0; // If the input is less than this constant, it is considered in a neutral position.
I'm going to assume this is a placeholder. If so, the value for our neutral stick position is in the project. I'll have to see if it's applied when finding the stick value, or when moving the motors, but I believe it's the former.
In any case, this constant may not be needed.

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	*/
This is a better formatted javadoc, but I have a few concerns. Namely, the length.

2022-12-31 02:36 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	*/
Javadocs are used to show a coder what the function is about, yes, but you seem to expect people to come to this file to read the comment. Instead, javadocs help us see what a function is just by hovering over it (depending on your ide)
this is a scary length of text

2022-12-31 02:38 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput, true)));
I was wrong about the error, but I'm still concerned about the existence of the third parameter.

2022-12-31 15:45 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	private final static double MAX_CTRL_SCALE = 1.0;
don't know how i didn't catch this earlier, but the practice is to write static before final. minor change, but noticeable.

2022-12-31 15:48 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/Constants.java
> +	public final static double MOVEMENT_EXPONENTIAL_BASE = 10.0;
similar to my comment below, this should be written "static final", like the variables below

2022-12-31 17:25 UTC, vladaviedov reviewed
Good work, but some things still need to be fixed

2022-12-31 17:25 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput, true)));
This is part of ManualDrive constructor, it will not compile otherwise.
I think having ramping as an option that can  be adjusted is perfectly valid.
This way we can toggle it during runtime.

2022-12-31 17:25 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +	*/
Yeah, the function comment should include a brief description of what the function does (abstractly), which parameters it takes and what it returns.

Like Rit said, IDEs will only pick up the header, so you should implementation details as comment in the body of the function instead.

2022-12-31 17:25 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
The way it's designed currently, this should be a function inside ManualDrive.

Now hypothetically, if this was used in another place, it should be a static function. The three fields are not altered in any way withing the object; it would make perfect sense for them to be either function parameters or constants.

2022-12-31 17:25 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +		if (_isMaxScalingFaster && (isControlNeutral || isControlMax) || !_isMaxScalingFaster && isControlNeutral) {
Notice that `isControlNeutral` is independent from `isMaxScalingFaster`

This should be equivalent, but more concise
`isControlNeutral || _isMaxScalingFaster && isControlMax`

2022-12-31 17:25 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +		else {
Push else back to line 52

2022-12-31 17:35 UTC, vladaviedov commented
> I believe I have made all the changes you guys wanted. Thanks for the help and review, and if you could help me or teach me how to interface with Shuffleboard to be able to turn on and off the ramping, that would be great! Thanks so much!

Yes, take a look at how switching between control schemes work.

In RobotContainer::initDashCommands, you can see how you would create a new dashboard command
```
tab.add("Double Control", new DashRunProcedure(this::controlDouble));
```

Notice here, the parameters to `add` are `(String, Command)`, which is why you need to use the `DashRunProcedure` wrapper.
The constructor takes a function reference which must be `void()`, so you'd create an new function in `RobotContainer` and pass it as the parameter.

Now writing the actual function is a little complicated.
To access the drive command you'd need to search the `_teleopPairs` list by subsystem and then do a cast into `ManualDrive`.
After that you should be able to figure out what to do.

2022-12-31 17:39 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput, true)));
I agree
I think having it, and ramping in general, be a part of ManualDrive is bad. Instead, include it in Drive, and still be able to toggle it.

2022-12-31 17:39 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +		else {
what he's saying:
} else {

2022-12-31 17:39 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +		if (_isMaxScalingFaster && (isControlNeutral || isControlMax) || !_isMaxScalingFaster && isControlNeutral) {
I think you have it right now so it makes sense to a viewer without a comment
Vlad's statement works too, but is much easier to calculate for the program. If you're concerned about readability, add a comment!

2022-12-31 17:39 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
I think this shouldn't be in ManualDrive at all.
Theoretically, we'd also want to ramp auto code, right? Therefore, ramping should be in Drive. It may be harder to implement shuffleboard and the like, but not too bad.

2022-12-31 18:17 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/Constants.java
> +	public final static double MOVEMENT_EXPONENTIAL_BASE = 10.0;
artifact from previous version... useless variable

2023-01-01 21:57 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
Why would we need ramping on the auto command? The auto drive command should calculate the motor spin values needed to move the robot to those positions, then implement them quickly, no?

2023-01-01 23:24 UTC, vladaviedov commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
There's an argument to be made either way.
I'm leaning towards to ramping on Auto because complicate things and probably make the commands inaccurate.

2023-01-01 23:32 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/util/ControlRamping.java
> +public class ControlRamping {
I think having the option to put ramping on auto is better, as it doesn't detract from the manual ramping, but allows ramping to be used in auto if that's ever necessary
Right now, I agree auto drive shouldn't be ramped, but if it's a refactoring difference, leaving the options open is preferable, in my opinion.

2023-01-02 04:40 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		_teleopPairs.add(new Pair<Subsystem, Command>(_drive, new ManualDrive(_drive, _controlInput, true)));
Also, I think the third parameter is unnecessary, and maybe against the point of robot container
I see robot container as holding all the big parts of the robot, like the drive system, climbers, and flywheel, for example, and activating and deactivating those parts at specific times.
From there, the specific parts do different things based on how and when their activated. ideally, this is done independently of the other parts.
ramping only deals with drive, at least for now, and isn't a big part on the robot. thus, i think the logic regarding ramping activation should be localized in drive, but still have a toggle command.

thank you for listening to my ted talk

2023-01-11 02:19 UTC, ElementalAlly commented
@fielia @vladaviedov Could you review it again? I believe I've fixed your comments... Thanks in advance!

2023-01-11 02:19 UTC, fielia requested changes

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
That shouldn't be an issue. Why do you think it would be an issue?

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/commands/manual/ManualDrive.java
> +	public void toggleAccRamping() {
javadoc comment! doesn't need to be complex, literally just `toggles acceleration ramping` would do.

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
>  	private MotorControllerGroup _leftMotors = new MotorControllerGroup(_left);
i would add a new line between the entry and motors, but it's not a big deal

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +
unnecessary new line

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 */
nice javadoc comment!

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private double limitValue(double value, double min, double max) {
is this function necessary? it's only used in one place
you could substitute in the logic into the calc method, and add a small `//` comment above stating why it's there

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	public void toggleAccRamping() {
1. javadoc!
2. why is this in both `ManualDrive.java` and `Drive.java`? if you're only calling the function from Drive, you don't need it in ManualDrive

2023-01-11 02:19 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
>  		_left[0].getEncoder().setPositionConversionFactor(WHEEL_DIAMETER * Math.PI / GEAR_RATIO);
i'd add a new line here too

2023-01-11 02:20 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
I thought it may have a specific reason...

2023-01-11 02:21 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private double limitValue(double value, double min, double max) {
more readable code?

2023-01-11 02:21 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	public void toggleAccRamping() {
Manual drive is redundant... oops

2023-01-11 02:21 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
I don't see anything that will become a problem either way.

2023-01-11 02:21 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
>  		_left[0].getEncoder().setPositionConversionFactor(WHEEL_DIAMETER * Math.PI / GEAR_RATIO);
Alright!

2023-01-11 02:22 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private double limitValue(double value, double min, double max) {
it's not that big of a deal here. if it were a repeated logic string used, then it works. here, its just in one place, and probably never going to be needed again. i believe adding the `//` comment will have the same effect

2023-01-11 02:24 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
I don't know what I was thinking... I did that when I had a previous version that may have required the order...

2023-01-11 02:25 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
that's fine! that's why pull requests are here: so we can double-check each other's work :)

2023-01-11 02:37 UTC, ElementalAlly commented
Sorry for the absolutely massive amounts of commits... I'm missing things left and right here :)

2023-01-11 02:37 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 */
Thanks!

2023-01-11 02:37 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		initTeleopCommands(); // Is it OK to change the order of these? Just want to guarantee that _manualDrive is always init before dashboard command changes a value in it...
yay!

2023-01-11 02:38 UTC, fielia requested changes

2023-01-11 02:38 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +		nextCtrlScale = Math.min(Math.max(nextCtrlScale, -MAX_CTRL_SCALE), MAX_CTRL_SCALE);
what does this min-max calculation do? if you're concerned about readability, adding a small line comment here would help clarify

2023-01-11 02:38 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
>  	private static final double MAX_CTRL_SCALE = 1.0;
Instead of having MAX_CTRL_SCALE and -MAX_CTRL_SCALE, maybe add another variable called MIN_CTRL_SCALE and set it to -1.0

2023-01-11 02:38 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +		nextCtrlScale = Math.min(Math.max(nextCtrlScale, -MAX_CTRL_SCALE), MAX_CTRL_SCALE);
also, if you're worried about the value exceeding -1 and 1, there's already a speed limiter that can be applied in `Drive.java`. The function is located in `Subsystem.java`, and one of the other subsystem files has an example of how it's used (`Acquisition.java` maybe?). instead of limiting it here, we can limit the values in Drive

2023-01-11 02:38 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +		nextCtrlScale = Math.min(Math.max(nextCtrlScale, -MAX_CTRL_SCALE), MAX_CTRL_SCALE);
oh we already do... oops

2023-01-11 02:45 UTC, fielia approved these changes, later dismissed
it's good to go! other than a few small description changes, ur good! nice work

2023-01-11 02:45 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		tab.add("Drive Acceleration Ramping", new DashRunProcedure(_drive::toggleAccRamping));
Instead of having the command name be the variable you're changing, maybe have something like "Toggle Drive Ramping"

2023-01-11 02:45 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param _isMaxScalingFaster if you push the joystick to its max, this determines whether it ramps faster
may be a bit nitpicky, but this can be reworded better
"determines whether pushing joystick to its max ramps faster" or something

2023-01-11 16:55 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/RobotContainer.java
> +		tab.add("Drive Acceleration Ramping", new DashRunProcedure(_drive::toggleAccRamping));
Just fixed this with the new commit

2023-01-11 16:55 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	 * @param _isMaxScalingFaster if you push the joystick to its max, this determines whether it ramps faster
Fixed this with the new commit

2023-01-12 01:26 UTC, fielia approved these changes, later dismissed

2023-01-12 01:26 UTC, the-goat-man commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
just curious what this represents

2023-01-12 01:53 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
The threshold between the target control scale and the current control scale that ramping stops and the current is set to the target.

2023-01-12 01:58 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
could you add that in a comment? i think that's all you need
also, ur wording is a bit confusing. `RAMPING_JUMP_THRESHOLD` is the minimum difference allowed between the target scale and current scale?

2023-01-12 14:17 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
If the distance is less than the threshold, the current will "jump" to the target

2023-01-12 23:22 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
basically, the minimum for having another iteration of the function
just say that!

2023-01-14 17:55 UTC, vladaviedov submitted a review, later dismissed

2023-01-14 22:22 UTC, ElementalAlly commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
Is there any way I can just make this change without you and vlad having to rereview it?

2023-01-14 22:28 UTC, fielia commented on src/main/java/org/recordrobotics/munchkin/subsystems/Drive.java
> +	private static final double RAMPING_JUMP_THRESHOLD = 0.1;
i don't think so

2023-01-15 16:48 UTC, ElementalAlly commented
Sorry for the trouble, but I added a small comment... Could you just rereview this quickly? Thanks!

2023-01-16 01:09 UTC, vladaviedov approved these changes

2023-01-16 01:28 UTC, merged